### PR TITLE
JoyceQu practice

### PR DESCRIPTION
**Pull request by sushidoggg**
-Delete the file that I accidentally merged.
-Add a new file for practicing use.

### CODE REVIEW

**Review by yechs — APPROVED** [review]

**Review by yechs — CHANGES_REQUESTED** [review]
I believe that you will need to do a `git pull` first on the master branch before you create the new branch from it (to avoid merge conflicts).

Now, you have to manually resolve this merge conflict on GitHub.com before merging this PR

**Comment by yechs** [comment]
Hold on, on web editor it displays that `these conflicts are too complex to resolve in the web editor` (because the file in conflict is renamed/deleted)

**Comment by yechs** [comment]
Merge conflict resolved

**Comment by sushidoggg** [comment]
Probably because I deleted the original file and changed that to UTF-8 without renaming it?
How can I solve this? Rename it?

2019-09-16 

qulecheng2004 



发件人：Ye Shu <notifications@github.com>
发送时间：2019-09-16 20:26
主题：Re: [Computerization/New-member-practice-commit] JoyceQu practice (#5)
收件人："Computerization/New-member-practice-commit"<New-member-practice-commit@noreply.github.com>
抄送："JoyceQu"<qulecheng2004@163.com>,"Author"<author@noreply.github.com>

Hold on, on web editor it displays that these conflicts are too complex to resolve in the web editor (because the file in conflict is renamed/deleted)

**Comment by yechs** [comment]
> Probably because I deleted the original file and changed that to UTF-8 without renaming it? How can I solve this? Rename it? 

Not exactly. I will explain this to you. Meanwhile please refer to the [Network page](https://github.com/Computerization/New-member-practice-commit/network).

1. in commit de15feb, you've added the file `代码.txt` in GB2312 encoding (let's give this file **State A**)
2. commit de15feb is merged into master branch with commit e65e946
3. in commit a3c1bbb, I've changed this file's encoding to UTF-8 (say, from **State A** to **State B**)
4. the commit a3c1bbb is merged into master branch in c1bc1a5

So far, the file in the `master` branch (the main branch) is good and in **State B**.

Let's see what happens next:

1. you continued to commit bbd555f and 72e5df5 in your old branch (you can see this more clearly in the [Network page](https://github.com/Computerization/New-member-practice-commit/network))
2. That means, you are editing on an older state, **State A**, of the file, and created a new state **State C** by deleting that file
3. When you create this pull request, and ask github to merge this branch (commit bbd555f and 72e5df5) into master branch, a merge conflict forms.

In a clearer sense:

- I've created **State B** from **State A**
- you've created **State C** from **State A**

When you prompt git to merge the changes. Git cannot tell whether you want to keep **State B** or **State C**. So we have to manually resolve this. Normally, we can resolve such a conflict within the GitHub Web Editor. However, the web editor cannot be used in the case when files are renamed or deleted, making the resolving process much more painful.

**Comment by yechs** [comment]
But anyway, the best way is to **totally avoid merge conflicts**, instead of trying to resolve them over and over again.

So, when you want to create a new branch, please follow these steps:

1. Checkout to master branch
2. pull from remote (also known as "sync changes")
3. Create new branch **from master**
4. checkout to your new branch and begin work

I have specifically stated that "do make sure the new branch is based on master branch" in [README.md of this repo](https://github.com/Computerization/New-member-practice-commit/blob/master/README.md#create-a-new-branch). Now I feel like I may need to elaborate on them and explain the rationales.

**Comment by yechs** [comment]
Of course, these are very abstract concepts. and _should be_ hard to understand at first. I can maybe find sometime to explain them to you during our next offline activity

**Comment by sushidoggg** [comment]
I think I cloned the branch before you changed that original file to UTF-8, and just made changes based on that original version. So I'll check if there is any updates on the master branch before pulling requests in the future. Sorry for asking you to spend extra efforts on changing and explaining. 

2019-09-16 

qulecheng2004 



发件人：Ye Shu <notifications@github.com>
发送时间：2019-09-16 20:55
主题：Re: [Computerization/New-member-practice-commit] JoyceQu practice (#5)
收件人："Computerization/New-member-practice-commit"<New-member-practice-commit@noreply.github.com>
抄送："JoyceQu"<qulecheng2004@163.com>,"Author"<author@noreply.github.com>

Of course, these are very abstract concepts. and should be hard to understand at first. I can maybe find sometime to explain them to you during our next offline activity

**Comment by yechs** [comment]
It's Okay. We've all experienced similar setbacks and learned from them. Don't feel back about them. You are making progress

**Pull request merged**
